### ISSUE TITLE
Change in terminal color when using Shell commands in trepl

### ISSUE THREAD

**Issue by ssakhavi** [torch/trepl#14]
Hi,

This is a new problem: when I use , for example, ```$clear``` to clear the screen in ```trepl```, everything goes blue-ish in the terminal window.

Fix?

**Comment by soumith** [comment]
cant seem to reproduce! what platform and shell?

**Comment by ssakhavi** [comment]
Linux 14.04, Bash

I didn't have problems before. I reinstalled torch using your repository
and this came up.

Can it be that there might be some conflict with my previous rocks ? I
think that they haven't been cleaned properly.

**Comment by soumith** [comment]
try using this script to cleanup:
https://github.com/torch/ezinstall/blob/master/clean-old.sh
