### ISSUE TITLE
loading a library at command-line fails to print the error + stack-trace

### ISSUE THREAD

**Issue by soumith** [torch/trepl#15]
The library loading at command-line with the -l flag is wrapped in pcalls, so if a library fails to load, all we see is: could not load xxxx, skipping

This is not great, as, when you want to debug something, you have to fallback to luajit to see  "why" the library isn't loading.

It would be nice to not only see "could not load xxxx, skipping" but also see the stack-trace on why it did not load.

**Comment by nicholas-leonard** [comment]
This also applies when we do `require 'library'`. If you are missing syntax like a `then`, th won't say why.
