### ISSUE TITLE
io.write does not behave as expected

### ISSUE THREAD

**Issue by fmassa** [torch/trepl#24]
When the `trepl` environment is on, `io.write` stops to behave as one would expect.  On `luajit`, I get the following behaviour: 
```
th> io.write('tst\n')
tst
th> require 'trepl'
th> io.write('tst\n')
tst
th> repl()
th> io.write('tst\n')
tst
file (0x7f08fd7ec400)
                         
```
It indeed prints the given string, but after calling `repl()` it also prints `file (0x7f08fd7ec400)`. Any thoughts about what might be causing this issue ?

**Comment by soumith** [comment]
trepl also prints the return values if you dont give a semi-colon, like matlab style.

io.write returns a file handle, and trepl returns that to screen as well.

try:
io.write('tst\n');
