### ISSUE TITLE
has license changed

### ISSUE THREAD

**Issue by alisabri** [torch/trepl#25]
Hi,
Thanks for sharing Trepl. I used (modified a bit) it in an online Lua REPL with torch support, tide (https://github.com/bitRadio/tide). The last time I checked license notification was "Copyright: MIT / BSD / Do whatever you want with it. Clement Farabet, 2013", so I kept it in sources. Should I change it acoording to current one ?

Regards,
Ali Sabri

**Comment by soumith** [comment]
right now the license is BSD. I think you're okay with licensing Tide under MIT and using a modified Trepl.

Tide looks really exciting, is it ready to try? I see pre-release tag on it.

**Comment by alisabri** [comment]
Hi, 
Thanks for the quick response. Yes it is ready to try.

Regards
