### ISSUE TITLE
No results matching query found

### ISSUE THREAD

**Issue by darshanime** [torch/trepl#27]
When I issue `luarocks install trepl`, I get the this error : `Error: No results matching query were found.`
`luarocks list` is :
 
Installed rocks:
----------------

cwrap
   scm-1 (installed) - /home/radar/anaconda/lib/luarocks/rocks

luarocks
   2.2.1-1 (installed) - /home/radar/anaconda/lib/luarocks/rocks

paths
   scm-1 (installed) - /home/radar/anaconda/lib/luarocks/rocks

torch
   scm-1 (installed) - /home/radar/anaconda/lib/luarocks/rocks

**Comment by soumith** [comment]
consult our google groups for fixes, or further issues as such. https://groups.google.com/forum/#!forum/torch7
