### ISSUE TITLE
Bad colours management

### ISSUE THREAD

**Issue by Atcold** [torch/trepl#34]
`setprintlevel(0)` removes colours output.
`noColors()` adds a tab after each line. So `setprintlevel(0)` has `noColors()` correct behaviour.

Both functions are bugged.

**Comment by Atcold** [comment]
@soumith, I found the bug. It's the trailing `\t` [here](https://github.com/torch/trepl/blob/f7960316998f24bd62aa2d1461a06f07e0196c55/init.lua#L270)! What can we do?

**Comment by soumith** [comment]
can you send a PR to fix this?

**Comment by Atcold** [comment]
@soumith, I wouldn't know how to remove the trailing `\t`, since it is necessary to space multi variables input of `print()`.
```bash
# Lua's print()
$ th -e "setprintlevel(0); print('abc')" | cat -A
abc$
# No coloured Torch's print()
$ th -e "noColors(); print('abc')" | cat -A
abc^I$
# Torch's print()
$ th -e "print('abc')" | cat -A
^[[0mabc^[[0m^I$
```
Any suggestion?

**Comment by Atcold** [comment]
Sweet! :+1:
