### ISSUE TITLE
module 'treplutils' not found

### ISSUE THREAD

**Issue by fabioperez** [torch/trepl#41]
When installing Torch with ezinstall (https://github.com/torch/ezinstall), I get the following error:

```
$ th
/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:40: module 'treplutils' not found:No LuaRocks module found for treplutils
        no field package.preload['treplutils']
        no file '/root/.luarocks/share/lua/5.1/treplutils.lua'
        no file '/root/.luarocks/share/lua/5.1/treplutils/init.lua'
        no file '/usr/local/share/lua/5.1/treplutils.lua'
        no file '/usr/local/share/lua/5.1/treplutils/init.lua'
        no file './treplutils.lua'
        no file '/usr/local/share/luajit-2.0.4/treplutils.lua'
        no file '/root/.luarocks/lib/lua/5.1/treplutils.so'
        no file '/usr/local/lib/lua/5.1/treplutils.so'
        no file './treplutils.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/share/lua/5.1/trepl/init.lua:40: in main chunk
        [C]: in function 'require'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:104: in main chunk
        [C]: at 0x00405850
```

If I remove lines 40 and 50 the error doesn't show up.

    40. local cutils = require 'treplutils'
    50. or (not cutils.isatty())

**Comment by soumith** [comment]
(1) Dont install torch with ezinstall, use the instructions on our website.

(2) Can you give the output log of:
luarocks install trepl

**Comment by fabioperez** [comment]
```
Installing https://raw.githubusercontent.com/torch/rocks/master/trepl-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/trepl-scm-1.rockspec... switching to 'build' mode
gcc -O2 -fPIC -I/usr/local/include -c readline.c -o readline.o
gcc -shared -o readline.so -L/usr/local/lib readline.o -lreadline
Updating manifest for /usr/local/lib/luarocks/rocks
trepl scm-1 is now built and installed in /usr/local/ (license: BSD)
```

**Comment by soumith** [comment]
ohhh, i know the issue, fixing it in a sec.
The rockspec is out of date on torch.rocks.

**Comment by soumith** [comment]
ok I just fixed it. 

luarocks install trepl

will fix it.

**Comment by fabioperez** [comment]
@soumith Thanks!

**Comment by jiapei100** [comment]
I've got exactly the same problem for now....
When I tried to start **th**, I got

 > jiapei:~$ th
> /usr/local/bin/lua: /usr/local/share/lua/5.3/luarocks/loader.lua:118: error loading module 'treplutils' from file '/usr/local/lib/lua/5.3/treplutils.so':
>         dynamic libraries not enabled; check your Lua installation
> stack traceback:
>         [C]: in local 'a_loader'
>         /usr/local/share/lua/5.3/luarocks/loader.lua:118: in function </usr/local/share/lua/5.3/luarocks/loader.lua:115>
>         (...tail calls...)
>         [C]: in function 'require'
>         /usr/local/share/lua/5.3/trepl/init.lua:40: in main chunk
>         [C]: in function 'require'
>         /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:104: in main chunk
>         [C]: in ?

**Comment by ParetoLife** [comment]
I have a similar/the same problem:

`fbook@fbook-HP-ZBook-Studio-G3:~/torch$ th
/home/fbook/torch/install/bin/lua: /home/fbook/torch/install/share/lua/5.2/luarocks/loader.lua:117: error loading module 'treplutils' from file '/home/fbook/torch/install/lib/lua/5.2/treplutils.so':
	/home/fbook/torch/install/lib/lua/5.2/treplutils.so: undefined symbol: luaL_register
stack traceback:
	[C]: in function 'a_loader'
	/home/fbook/torch/install/share/lua/5.2/luarocks/loader.lua:117: in function </home/fbook/torch/install/share/lua/5.2/luarocks/loader.lua:114>
	(...tail calls...)
	[C]: in function 'require'
	/home/fbook/torch/install/share/lua/5.2/trepl/init.lua:40: in main chunk
	[C]: in function 'require'
	...book/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:104: in main chunk
	[C]: in ?`

**Comment by dmihis** [comment]
@soumith, got the same error even though trepl successfully installed: (using lua 5.1)

/usr/local/bin/luajit: /usr/lib/torch-trepl/th:103: module 'trepl' not found:
        no field package.preload['trepl']
        no file './trepl.lua'
        no file '/usr/local/share/luajit-2.0.4/trepl.lua'
        no file '/usr/local/share/lua/5.1/trepl.lua'
        no file '/usr/local/share/lua/5.1/trepl/init.lua'
        no file './trepl.so'
        no file '/usr/local/lib/lua/5.1/trepl.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/lib/torch-trepl/th:103: in main chunk
        [C]: at 0x004060e0
