### ISSUE TITLE
Loop or previous error loading module 'torch'

### ISSUE THREAD

**Issue by AdityaChaganti** [torch/trepl#51]
Two of the other issues seemed similar, but could someone explain the issue (and a fix) to me in simple words? I'm not sure why this is happening. I run "th file.lua -input_h5 -input_json", and the following comes up:

/home/adityac/torch/install/bin/luajit: /home/adityac/torch/install/share/lua/5.1/trepl/init.lua:384: loop or previous error loading module 'torch'
stack traceback:
	[C]: in function 'error'
	/home/adityac/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	train.lua:2: in main chunk
	[C]: in function 'dofile'
	...tyac/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x004064d0

**Comment by AdityaChaganti** [comment]
@soumith

**Comment by soumith** [comment]
run the command:
luajit -ltorch
luajit -llibtorch

See what errors you get

**Comment by AdityaChaganti** [comment]
@soumith 

luajit -ltorch
luajit: /home/adityac/.luarocks/share/lua/5.1/torch/init.lua:13: cannot load '/home/adityac/.luarocks/lib/lua/5.1/libtorch.so'
stack traceback:
	[C]: in function 'require'
	/home/adityac/.luarocks/share/lua/5.1/torch/init.lua:13: in main chunk
	[C]: at 0x0046b010
	[C]: at 0x004064d0

luajit -llibtorch
luajit: error loading module 'libtorch' from file '/home/adityac/.luarocks/lib/lua/5.1/libtorch.so':
	libluaT.so.0: cannot open shared object file: No such file or directory
stack traceback:
	[C]: at 0x0047a730
	[C]: at 0x0046b010
	[C]: at 0x004064d0

**Comment by soumith** [comment]
ls ~/torch/install/lib

Does it have libluaT.so.0 ?

**Comment by AdityaChaganti** [comment]
Nope, it's missing.

**Comment by soumith** [comment]
can you try: luarocks install torch

**Comment by AdityaChaganti** [comment]
That worked! Thanks :)

What caused that, exactly?

**Comment by soumith** [comment]
i'm not sure either tbh!
